### ISSUE TITLE
Obtain dataset for pretraining ProteinBERT

### ISSUE THREAD

**Issue by duongvtt96** [nadavbra/protein_bert#12]
Hi, I would like to pretrain the ProteinBERT model with a smaller dataset, such as human proteins in UniRef90. I have searched in between UniProtKB and UniRef90 website but could not find out how the obtain the .xml.gz file containing GO annotations similar to your uniref90.xml.gz file.
Could you explain how to get that kind of input file?

Thank you!

**Comment by ddofer** [comment]
The easiest alternative would be to download just Swissprot (most, but not all human proteins are there), or Uniref50:
https://www.uniprot.org/downloads
https://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.xml.gz
