### ISSUE TITLE
Pretraining from scratch - Error while creating the h5 dataset file? 

### ISSUE THREAD

**Issue by fridalon** [nadavbra/protein_bert#14]
Hi,

I'm trying to pretrain from scratch with UniRef50. 
Until running the script "create_uniref_h5_dataset" (step 1 (5)) it seems like everything's going fine.
After running this script, the output log seems like it did some work (took 5.5 hours) except that the 2 last lines are -
'Finished. Failed finding the sequence for 51333317 of 51333317 records.'
'Done'.
And - **the dataset.h5 file weight 290Kb**. Is this really an error? the size is too small for this file?

Thank you for your help,
Alon

**Comment by nadavbra** [comment]
Hi @fridalon,

It indeed seems to have failed for some reason.
Did you try creating the dataset for UniRef90 (the dataset we used originally to train ProteinBERT). I can't think of any reason why it would work for UniRef90 and not UniRef50, but I think that it's worth starting with the exact same conditions we used (for the sake of debugging). Also, if it still doesn't work, could you attach the full logs you get from the script?

**Comment by fridalon** [comment]
Hi @nadavbra ,

I found the problem. in "uniref_dataset.py" file, in the function **load_seqs_and_annotations** - 

<img width="647" alt="image" src="https://user-images.githubusercontent.com/42042001/162470521-7e3e6edb-50c6-45e6-8740-126fa4b15966.png">

I will run and let you know if it worked.
Thanks

**Comment by fridalon** [comment]
@nadavbra 
can close the issue. thanks

**Comment by skr3178** [comment]
@nadavbra @fridalon 
Can you say how much compute power is needed to run from scratch?
Say A100 GPU running for 1 month or something else?


````
If, instead of using the existing model weights, you would like to train from scratch, then follow the steps below. We warn that this is a long process (we pretrained the current model for a whole month), and it also requires a lot of storage (>1TB).
````

**Comment by nadavbra** [comment]
It looks like a stronger GPU than the one we used, so yes, 1 month over a single GPU should get you to the same performance.
