### ISSUE TITLE
Inputs types while pretraining alone

### ISSUE THREAD

**Issue by fridalon** [nadavbra/protein_bert#16]
Hi @nadavbra,

Im trying to pretrain the model on antibodies dataset (without annotations). Does the next screenshot is a good example of inputs to the model? in the sense of types (for example - does **seqs** should be an array of strings? or maybe array of arrays?)

![image](https://user-images.githubusercontent.com/42042001/164744777-f2c5d8e0-cfe3-4945-b20e-845abfc317ce.png)

Thank you very much for your help
Alon

**Comment by nadavbra** [comment]
Just to make sure I understand the context of your question, you are essentially writing your own code for pretraining the model on your own dataset, right? If so, I think [this short thread](https://github.com/nadavbra/protein_bert/issues/10) will be useful for you.

Overall these inputs seem reasonable (assuming you don't have GO annotations), but that would of course depend on how exactly you use them to pretrain the model.

**Comment by fridalon** [comment]
@nadavbra thank you for your answer. 
Yes I am changing a bit your code. I saw this thread and I also changes the DatasetHandler object to this one - 

![image](https://user-images.githubusercontent.com/42042001/164887508-b8670266-dfe0-4f4a-a29a-d0cd7164d9ba.png)

If you dont think I need to change something else you can close the issue. Thank you very much

**Comment by nadavbra** [comment]
I just meant the overall flow of your code. Everything you do seems reasonable, but it just depends on your overall implementation.
I'd be curious to know whether it ended up working in the end.
