### ISSUE TITLE
UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.

### ISSUE THREAD

**Issue by JudeWells** [nadavbra/protein_bert#19]
In model_generation.py:

``model.compile(optimizer = self.optimizer_class(lr = self.lr,...``

should be changed to:

``model.compile(optimizer = self.optimizer_class(learning_rate = self.lr,...``

To avoid the following deprecation warnings:
``UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.  super(Adam, self).__init__(name, **kwargs)``

**Comment by nadavbra** [comment]
Thank you Jude for the code update!
