### ISSUE TITLE
Finetuning question

### ISSUE THREAD

**Issue by xixinhy** [nadavbra/protein_bert#21]
I want to use your method to fine-tune the problem I have done,but I cannot download 
ftp.cs.huji.ac.il/users/nadavb/protein_bert/protein_benchmarks
please, what shoulde I do ?

**Comment by nadavbra** [comment]
@xixinhy See [here](https://github.com/nadavbra/protein_bert/issues/7) and [here](https://github.com/nadavbra/protein_bert/issues/5).
