### ISSUE TITLE
Visualizing Attention

### ISSUE THREAD

**Issue by miladansari** [nadavbra/protein_bert#22]
Hi, I'm trying to use BertViz for visualizing attentions, I got an error for not correct number of dimensions, is it possible to somehow manage this error?

![Screenshot (878)](https://user-images.githubusercontent.com/80484295/170208877-f547949e-dd5d-4243-a337-23a4a942e0b9.png)

**Comment by nadavbra** [comment]
@miladansari  I'm not sure what BertViz is, but keep in mind that ProteinBERT uses global attention which is a 3D tensor (batch x heads x seq_len) as opposed to most transformers that use self-attention which is a 4D tensor (batch x heads x seq_len x seq_len). This is actually part of the point of using global attention - it is more compact and easier to visualize. On our notebook we have a section with code for visualizing ProteinBERT's attention. I hope that helps.

**Comment by miladansari** [comment]
Great, Thanks
