### ISSUE TITLE
the benchmarks dataset FTP seems to be invalid, Could you deal with it

### ISSUE THREAD

**Issue by zchaong** [nadavbra/protein_bert#25]
the benchmarks dataset FTP seems to be invalid, Could you deal with it

**Comment by zchaong** [comment]
the link above seems to be failed, I can't access it.



And I have tried&nbsp;to open it with Internet Explorer, or a dedicated FTP client such as FileZilla. But failed.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nadavbra/protein_bert"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月14日(星期二) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nadavbra/protein_bert] the benchmarks dataset FTP seems to be invalid, Could you deal with it (Issue #25)





 
@zchaong You haven't provided any specific details about the error you are getting. Please try to see if any of these help:
 #5
 #7

**Comment by nadavbra** [comment]
What is the exact link you are trying to access and failing? What error are you getting?
