### ISSUE TITLE
The annotation number does not match your pretrained model

### ISSUE THREAD

**Issue by zhongguojie1998** [nadavbra/protein_bert#26]
Hi Protein_bert team,

Thanks for providing such useful model. I found one weird thing about your pretrained model, after I created the uniref90 database and merged with GO database through the pipeline you provided, I got 9211 annotation records. This is different from your number in the manuscript, 8943. Would you mind taking a look into this?

**Comment by nadavbra** [comment]
@zhongguojie1998 I think it makes sense. UniProt and GO constantly update their databases, so it makes sense that more annotations will be added over time.

**Comment by dsaeedeh** [comment]
@nadavbra Which release date of uniref90 did you use for pertaining?

**Comment by nadavbra** [comment]
@dsaeedeh Please see my response to [your other issue](https://github.com/nadavbra/protein_bert/issues/29).
