### ISSUE TITLE
release date of uniref90

### ISSUE THREAD

**Issue by dsaeedeh** [nadavbra/protein_bert#29]
Could you please mention which release date of uniref90 you used for pertaining?

**Comment by nadavbra** [comment]
@dsaeedeh 
We downloaded this dataset: ftp.uniprot.org/pub/databases/uniprot/uniref/uniref90/uniref90.fasta.gz (at the time of working on the project in early 2021).

**Comment by dsaeedeh** [comment]
Thank you for your response. 
I checked your paper about the size of the Uniref90 you used and you mentioned that it is ~106 M. Then I checked the sizes of different releases of Uniref90 that existed on FTP and I noticed that release 2019-11 has the size of ~106 M. I think you used version 2019-11 for your paper.

**Comment by nadavbra** [comment]
@dsaeedeh Thank you for checking this!
