### ISSUE TITLE
Hello World

### ISSUE THREAD

**Issue by BiochemStudent2** [nadavbra/protein_bert#31]
Can you please post a hello world code example? I need to use the pre-trained model to predict one missing residue in a single sequence. I have spent hours trying to figure it out using the demo examples and code snippets in the issues, but haven't had any success. I would be really grateful for any help with this.

**Comment by nadavbra** [comment]
@BiochemStudent2 
You can try something along these lines:

```pyhton
from proteinbert import load_pretrained_model

seq = 'MDDADPEERNYDNMLKMLSDLNKDLEKLLEEMEKISVQATWMAYDMVVMRTNPTLAESMRRLEDAFVNCKEEMEKNWQELLHETKQRL'
seq_len = 512

pretrained_model_generator, input_encoder = load_pretrained_model()
X = input_encoder.encode_X([seq], seq_len)
model = pretrained_model_generator.create_model(seq_len)
y_seq, y_annotations = model.predict(X, batch_size = 1)
```

**Comment by BiochemStudent2** [comment]
Thank you so much! This works great.

**Comment by ZakiaSalod** [comment]
> seq_len

Hi there.

For the seq_len specified in this code, do we have to set the seq_len here, to be the same value as 'seq_len' OR the 'final_seq_len' we used during fine tuning, if we are now trying to use the fine tuned model, to now do predictions based on the fine tuning? As we have the seq_len and final_seq_len as different values. Kindly advise.

**Comment by nadavbra** [comment]
@ZakiaSalod The model is designed such that it should be quite flexible about seq_len and work reasonably well with different values even without further training of the model (that's in fact one of the motivation of pre-training it with different sequence lengths and fine-tuning it with seq_len and final_seq_len that are different). Having said that, I expect that a seq_len equal to the original seq_len (not final_seq_len) used during fine-tuning may provide slightly better performance. However, if a larger seq_len is called for (e.g. if you need to process longer sequences) don't hesitate to use larger values.
