### ISSUE TITLE
finetune with dataset of different length sequences

### ISSUE THREAD

**Issue by vuhongai** [nadavbra/protein_bert#32]
Dear authors,

Thank you for sharing your great work. 
I would like to fine-tune your pretrained model on my dataset. The only problem is that sequences in the dataset contain various lengths. I wonder if the model is still suitable for this task.

Bests,
Ai

**Comment by nadavbra** [comment]
Hi @vuhongai,

ProteinBERT can definitely handle sequences of different lengths (it will automatically pad all the sequences shorter than the seq_len you define).

**Comment by vuhongai** [comment]
Thank you for your response.
