### ISSUE TITLE
final epoches with different length in finetuning the model

### ISSUE THREAD

**Issue by vuhongai** [nadavbra/protein_bert#33]
Dear authors,

Could you please explain for me why we need to train the model with extra epoches with different length (final_seq_len)? Is that to make the finetuned model better reassemble your pre-trained conditions, or you found that it results in better performance?

[https://github.com/nadavbra/protein_bert/blob/2090b78f09e70f0b960d7b591bf80d3d411c9d3f/proteinbert/finetuning.py#L59-L64](url)
`    if n_final_epochs > 0:
        log('Training on final epochs of sequence length %d...' % final_seq_len)
        final_batch_size = max(int(batch_size / (final_seq_len / seq_len)), 1)
        encoded_train_set, encoded_valid_set = encode_train_and_valid_sets(train_seqs, train_raw_Y, valid_seqs, valid_raw_Y, input_encoder, output_spec, final_seq_len)
        model_generator.train(encoded_train_set, encoded_valid_set, final_seq_len, final_batch_size, n_final_epochs, lr = final_lr, callbacks = callbacks, \
                freeze_pretrained_layers = False)`

And how the final finetuned model should be created? 
`model_generator.create_model(seq_len)` or  `model_generator.create_model(final_seq_len)` 

Thank you for your help.
Ai

**Comment by nadavbra** [comment]
@vuhongai We found that training the model on two different sequence lengths make it better generalize to a variety of sequence lengths (including lengths not included in the training). Once the model is trained, you should be able to use it with whatever seq_len you want (for efficiency reasons, it might be best to invoke it on a batch of sequences with not-too-different lengths and take seq_len to be the maximum among those lengths).

**Comment by vuhongai** [comment]
Thank you for your insight. 
Bests,
Ai
