### ISSUE TITLE
Global feature extraction

### ISSUE THREAD

**Issue by xixinhy** [nadavbra/protein_bert#36]
hi，Is the global feature extracted by PROTEINBERT model corresponding to the original label？

**Comment by nadavbra** [comment]
Could you please clarify your question? I'm not sure what you mean by "the global feature extracted by ProteinBERT" and "the original label".

**Comment by xixinhy** [comment]
Wasn't the initial input a sequence and a label? I want to know if the extracted global feature vector corresponds one-to-one to the original input label, that is, if the extracted global feature vector corresponds to the order of the original sequence?

**Comment by nadavbra** [comment]
If you refer to the 8943-dimensional vector of GO annotations - then yes, it's provided both as input and as output of the same GO annotation at each position. You may find the discussion in issue https://github.com/nadavbra/protein_bert/issues/6 relevant.

**Comment by xixinhy** [comment]
I entered a biomolecular structure instead of a Go comment. I want to get the features of the sequence. is the feature I need to extract a local feature instead of a global one?

**Comment by nadavbra** [comment]
I don't understand your question. Could you please elaborate on what you did / want to do?

**Comment by xixinhy** [comment]
I'm sorry, maybe my expression isn't perfect,  I want to use this model of yours, enter my biomolecular structure, to get the feature vector, but I'm not sure if I should use local or global features, the other question is, do I want to know if the order of the features I get is the same as the order of the Biomolecular Structure I entered?

**Comment by xixinhy** [comment]
I'm sorry, maybe my expression isn't perfect, I want to use this model of yours, enter my biomolecular structure, to get the feature vector, but I'm not sure if I should use local or global features, And another problem is, do I want to know if the order of the features I get is the same as the order of the Biomolecular Structure I entered?

**Comment by nadavbra** [comment]
If you want to use the pre-trained model, it only takes protein sequence and (optionally) GO annotations as input. If you want to use structure input, you should train a model that accepts that as input (optionally also with features/outputs from ProteinBERT).

**Comment by nadavbra** [comment]
So you want to train a model that takes a protein sequence as input and outputs the structure of that protein?

**Comment by xixinhy** [comment]
No, no ，I want the eigenvectors  of that protein, but I don't know if it's global or local. What do you suggest？

**Comment by nadavbra** [comment]
If you want me to be able to help you, you will have to be clearer about what you're hoping to achieve.

**Comment by xixinhy** [comment]
My goal is that I want to do the classification task of protein sequences, but the number of my protein is only more than 400
