### ISSUE TITLE
GO annotations are unavailable

### ISSUE THREAD

**Issue by r-kellerm** [nadavbra/protein_bert#39]
Hello,

Thank you for the great publication and for sharing the code.
I'd like to pretrain the model - but cannot find the GO metadata from CAFA -- the link https://www.biofunctionprediction.org/cafa-targets/cafa4ontologies.zip is broken.
Is there an alternative location of which the GO data can be downloaded from?

Thanks!

**Comment by nadavbra** [comment]
Try to contact the CAFA organizers:
https://biofunctionprediction.org/contact/

**Comment by r-kellerm** [comment]
Thanks for the quick response! Sent a request to upload it again.

**Comment by nadavbra** [comment]
@r-kellerm I wonder if you heard back from CAFA and if you'd be willing to share the solution you found (for the benefit of other users).

**Comment by r-kellerm** [comment]
@nadavbra - no, haven't heard back. Skipped the pretraining for now.

**Comment by nadavbra** [comment]
The GO annotations can also be downloaded directly from the [Gene Ontology website](http://geneontology.org/docs/download-go-annotations/), but it may require writing some new code to process the different format of the data.

**Comment by r-kellerm** [comment]
Thanks, will check this out.
