### ISSUE TITLE
Generate sequence based on natural one

### ISSUE THREAD

**Issue by avivlazar** [nadavbra/protein_bert#43]
Hi,
First of all, thank you for sharing ProteinBERT code.
I read the article as part of my thesis, and started playing with the model.

My questions:
1) How may I generate a new sequence by ProteinBERT which based on natural sequence?
For example:
Natural seq: "DQSVRKLVRKLPDEGLDREKVKTYLDKLGVDREELQKFSDAIGLESSGGS"
A new generated seq: "GSSDIEITVEGKEQADKVIEEMKRRNLEVHVEEHNGQYIDKASLESSGGS"

2) In generation process, is it possible to define which station/s in natural sequence I want ProteinBERT will change? if yes - how?
Example: I want to change only the 3th station in sequence, so:
Natural seq: "DQSV..."
Possible generated sequence: "DQGV..."

Best Regards,
Aviv.

**Comment by ddofer** [comment]
Hi, 
 Pbert isn't designed as a causal Generative model.  It's unsuited for generating sequences from scratch.  However,  It is well suited for filtering or ranking candidate generated sequences.
