### ISSUE TITLE
Restore amino acid sequence from local_representations or global_representations

### ISSUE THREAD

**Issue by bg-uni** [nadavbra/protein_bert#45]
Hello, 
I have a question.

Is there any way to recover the original one-dimensional amino acid sequence from local_representations or global_representations?

The code is as follows.

model = get_model_with_hidden_layers_as_outputs(pretrained_model_generator.create_model(seq_len))
X = input_encoder.encode_X(seqs, seq_len)
local_representations, global_representations= model.predict(X, batch_size = batch_size)

Thanks for your help!

**Comment by nadavbra** [comment]
Why do you want to recover the original amino-acid sequence from the representations?
ProteinBERT, like all language models, is an autoencoder, meaning that it tries to predict the correct amino-acid sequence from a noised one, so in principle if you take the output of the last hidden layer (from the local representations) and feed it into the output layer of the model, you should get predictions that are similar to the input sequence (but reflect the model's predictions of which input residues make more or less sense, so it won't necessarily be exactly the same as the input). But then again, why would you want to get the input specifically?

**Comment by Big-Gate** [comment]
Thank you for your answer.
My explanation was incorrect. My goal is not to recover the original input data (1D amino acid sequence), but to predict a 1D amino acid sequence using the output of some last hidden layer (from a local representation).
I understand that if I feed the output layer of the model, I can get a prediction similar to the input sequence, but can you show me exactly how to do this with sample code?

**Comment by nadavbra** [comment]
I'm sorry but I don't think I'll have the time to write this code. It sounds like a combination of pretty standard keras operations: you basically need to slice the relevant layers from your output and model (which is specified [here](https://github.com/nadavbra/protein_bert/blob/master/proteinbert/conv_and_global_attention_model.py)) and invoke the relevant layer on the relevant output. To learn more about how to use keras, they have pretty good documentations and tutorials on their [website](https://keras.io/).
