### ISSUE TITLE
Cannot convert a symbolic Tensor

### ISSUE THREAD

**Issue by QUEST2179** [nadavbra/protein_bert#49]
Dear Developer,

tried to run Fine-tune the model for the signal peptide benchmark in demo but got the following error, could you please help? Thanks!

  File "C:\Users\miniconda3\envs\tensor25\lib\site-packages\tensorflow\python\framework\ops.py", line 870, in __array__
    " a NumPy call, which is not supported".format(self.name))
NotImplementedError: Cannot convert a symbolic Tensor (seq-merge1-norm-block1/mul_1:0) to a numpy array. This error may indicate that you're trying to pass a Tensor to a NumPy call, which is not supported

**Comment by nadavbra** [comment]
Can you copy the code you were trying to run? Was it our code exactly or did you modify it? Please also provide the full stack trace.
