### ISSUE TITLE
Question on stability.valid.csv

### ISSUE THREAD

**Issue by CDieterich** [nadavbra/protein_bert#50]
Dear all,

I noticed the following:

wc -l stability.*csv
  12852 stability.test.csv
  53615 stability.train.csv
   2513 stability.valid.csv
  68980 total

Now, when I look at stability.valid.csv in particular, all sequences end with "ESSGGS".

Is there any particular reason for this ?

Likewise, the number of records appears quite low in stability.valid.csv

Best wishes,

Christoph

**Comment by CDieterich** [comment]
I am referring to : https://github.com/nadavbra/protein_bert#downloading-the-supervised-benchmarks

**Comment by ddofer** [comment]
the sequences are mutants from the same base WT sequence. You can check the source paper for the ful ldetails
