### ISSUE TITLE
Clustering protein sequences

### ISSUE THREAD

**Issue by AlejandroSanchezCano** [nadavbra/protein_bert#52]
Good afternoon, devs. I would like to use ProteinBert to perform protein sequence-based clustering. I have several questions:

- Is it possible with this tool?
- Would training it from scratch be very beneficial? (it's a step I'd like to skip)
- How would I apply the model to a set of sequences? I do not find any guidance in the README file

Thank you in advance

**Comment by r-kellerm** [comment]
Hello,

I'm not the developer of this package but can try to answer.
1. You can extract the embeddings and run clustering on them, e.g.
```
from proteinbert import load_pretrained_model
from proteinbert.conv_and_global_attention_model import get_model_with_hidden_layers_as_outputs

pretrained_model_generator, input_encoder = load_pretrained_model()
model = get_model_with_hidden_layers_as_outputs(pretrained_model_generator.create_model(seq_len))
encoded_x = input_encoder.encode_X(seqs, seq_len)
local_representations, global_representations = model.predict(encoded_x, batch_size=batch_size)
# Do clustering based on local_representations, global_representations
```
2. Pre-training from scratch is beneficial in case you have additional datasets or if you would like to modify the model architecture or the training flow. For clustering or other fine-tuning tasks you don't need to run the training from scratch.
3. See below - you first encode the input sequences using `input_encoder.encode_X(seqs, seq_len)` and then send the encoded inputs for inference through `model.predict(encoded_x, batch_size=batch_size)`

Good luck!

**Comment by nadavbra** [comment]
I fully endorse @r-kellerm 's answer. Clustering protein sequences based on ProteinBERT's embeddings seems like a sensible thing to do if you want proteins that are functionally similar to cluster together (but I've never actually tried that).

**Comment by ddofer** [comment]
Indeed - take the embeddings and cluster them. I can confirm that this works really well for many tasks, even without fine-tuning (We have another paper using this approach - 

```
Detecting Anomalous Proteins Using Deep Representations
Tomer Michael-Pitschaze, Niv Cohen, Dan Ofer, Yedid Hoshen, Michal Linial
bioRxiv 2023.04.03.535457; doi: https://doi.org/10.1101/2023.04.03.535457
```
https://www.biorxiv.org/content/10.1101/2023.04.03.535457v1
