### ISSUE TITLE
Using ProteinBERT

### ISSUE THREAD

**Issue by yasmeen1000** [nadavbra/protein_bert#54]
!wget ftp://ftp.cs.huji.ac.il/users/nadavb/protein_bert/epoch_92400_sample_23500000.pkl
model = torch.load("/content/epoch_92400_sample_23500000.pkl")

ERRORS
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-9-7a3413209e86>](https://localhost:8080/#) in <cell line: 1>()
----> 1 model = torch.load("/content/epoch_92400_sample_23500000.pkl")

1 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in _legacy_load(f, map_location, pickle_module, **pickle_load_args)
   1033     magic_number = pickle_module.load(f, **pickle_load_args)
   1034     if magic_number != MAGIC_NUMBER:
-> 1035         raise RuntimeError("Invalid magic number; corrupt file?")
   1036     protocol_version = pickle_module.load(f, **pickle_load_args)
   1037     if protocol_version != PROTOCOL_VERSION:

RuntimeError: Invalid magic number; corrupt file?

**Comment by nadavbra** [comment]
@yasmeen1000 Maybe downloading failed? Try to delete and re-download the pkl file (and make sure it's downloaded properly).

**Comment by yasmeen1000** [comment]
I have tried several times on Google Colab, but it didn't work.

**Comment by nadavbra** [comment]
What's the size of the file you downloaded?

**Comment by nadavbra** [comment]
@yasmeen1000 
Yes that's the correct file size.
But only now I see - why are you trying to load it with pytorch?

**Comment by yasmeen1000** [comment]
"Because I wanted to test the model and see the results, do you suggest a better way to do that?"

**Comment by r-kellerm** [comment]
@yasmeen1000 - You should load it with pickle, see [load_pretrained_model_from_dump](https://github.com/nadavbra/protein_bert/blob/443129f062043ba44e3fdcb97ca7b47627861db0/proteinbert/model_generation.py#L155)

```
with open(dump_file_path, 'rb') as f:
        n_annotations, model_weights, optimizer_weights = pickle.load(f)
if not load_optimizer_weights:
        optimizer_weights = None
    
model_generator = PretrainingModelGenerator(create_model_function, n_annotations, create_model_kwargs = 
            create_model_kwargs, optimizer_class = optimizer_class, lr = lr, \
            other_optimizer_kwargs = other_optimizer_kwargs, annots_loss_weight = annots_loss_weight, model_weights = 
            model_weights, optimizer_weights = optimizer_weights)
input_encoder = InputEncoder(n_annotations)
```

**Comment by yasmeen1000** [comment]
"I have a project at my university where I am designing a website that allows the user to input a protein, and using a trained model, I would output the results to them. However, I am unsure of how to do this as I have not been able to test the trained model. Can you help me with this?"

**Comment by yasmeen1000** [comment]
Excuse me, could you please provide me with some information about the trained model such as its components, input format, and expected output format?
