### ISSUE TITLE
protein length problem

### ISSUE THREAD

**Issue by yasamantaebi** [nadavbra/protein_bert#57]
I have a data set which contains about 5000 protein sequence and most of the them lengths is about 100-200. The fine-tune model starts lengths is 512 and decrease it wont start the training process. Any idea what should I do for short sequences ?

**Comment by nadavbra** [comment]
You have two options:
1. Just use a small `seq_len` (e.g. 200) - I think it should work fine (the model should handle changing sequence lengths) and be more efficient.
2. Alternatively, just use `seq_len=512` (the model should handle padding fine)
Either way, the framework will handle padding for you.
