### ISSUE TITLE
Issue Fine-tuning in Colab

### ISSUE THREAD

**Issue by williamtbarker** [nadavbra/protein_bert#60]
Sorry, me again... I have the model working fine on my IDE but when switching to google Colab I get the following error during the training phase:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-18-c45b5eb21378>](https://localhost:8080/#) in <cell line: 44>()
     42 
     43 # Fine-tune the model on your data
---> 44 finetune(
     45     model_generator, input_encoder, output_spec,
     46     train_data['seq'], train_data['label'], valid_data['seq'], valid_data['label'],

2 frames
[/usr/local/lib/python3.10/dist-packages/proteinbert/model_generation.py](https://localhost:8080/#) in update_state(self, model)
     33     def update_state(self, model):
     34         self.model_weights = copy_weights(model.get_weights())
---> 35         self.optimizer_weights = copy_weights(model.optimizer.get_weights())
     36 
     37     def _init_weights(self, model):

AttributeError: 'Adam' object has no attribute 'get_weights'

**Comment by williamtbarker** [comment]
Here is the full stack trace:

[2023_07_24-23:23:49] Training set: Filtered out 0 of 45 (0.0%) records of lengths exceeding 798.
[2023_07_24-23:23:49] Validation set: Filtered out 0 of 6 (0.0%) records of lengths exceeding 798.
[2023_07_24-23:23:49] Training with frozen pretrained layers...
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.
Epoch 1/40
2/2 [==============================] - ETA: 0s - loss: 1.1092 WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 23s 7s/step - loss: 1.1092 - val_loss: 0.4038 - lr: 0.0100
Epoch 2/40
2/2 [==============================] - ETA: 0s - loss: 0.7922WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 7s 3s/step - loss: 0.7922 - val_loss: 0.2230 - lr: 0.0100
Epoch 3/40
2/2 [==============================] - ETA: 0s - loss: 0.6029WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 8s 3s/step - loss: 0.6029 - val_loss: 0.1079 - lr: 0.0100
Epoch 4/40
2/2 [==============================] - ETA: 0s - loss: 0.4292WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 10s 3s/step - loss: 0.4292 - val_loss: 0.0509 - lr: 0.0100
Epoch 5/40
2/2 [==============================] - ETA: 0s - loss: 0.2681WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 7s 2s/step - loss: 0.2681 - val_loss: 0.0425 - lr: 0.0100
Epoch 6/40
2/2 [==============================] - ETA: 0s - loss: 0.2646WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0024999999441206455.
2/2 [==============================] - 8s 2s/step - loss: 0.2646 - val_loss: 0.0672 - lr: 0.0100
Epoch 7/40
2/2 [==============================] - ETA: 0s - loss: 0.1844WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0006249999860301614.
2/2 [==============================] - 7s 3s/step - loss: 0.1844 - val_loss: 0.0759 - lr: 0.0025
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-21-c45b5eb21378>](https://localhost:8080/#) in <cell line: 44>()
     42 
     43 # Fine-tune the model on your data
---> 44 finetune(
     45     model_generator, input_encoder, output_spec,
     46     train_data['seq'], train_data['label'], valid_data['seq'], valid_data['label'],

2 frames
[/usr/local/lib/python3.10/dist-packages/proteinbert/model_generation.py](https://localhost:8080/#) in update_state(self, model)
     33     def update_state(self, model):
     34         self.model_weights = copy_weights(model.get_weights())
---> 35         self.optimizer_weights = copy_weights(model.optimizer.get_weights())
     36 
     37     def _init_weights(self, model):

AttributeError: 'Adam' object has no attribute 'get_weights'

**Comment by nadavbra** [comment]
It looks like a keras version problem. Try to use the same version of keras that worked for you on your IDE.
