### ISSUE TITLE
Enquiry on dataset for pre-training

### ISSUE THREAD

**Issue by dhui-nvidia** [nadavbra/protein_bert#61]
Hi your work is really interesting and I would like to learn more about the dataset!

I would try out the steps myself but it seems there are some parts missing, along with the dataset being extremely large.

Firstly, would you have samples of how the pre-training dataset would look like? I assume they are sequence->GOTERM pairs?

Secondly, what is the reason for downloading both XML and FASTA for Uniref90. Wouldn't XML filetype contain all the information you would need? 

Lastly, what is metadata of GO from CAFA that you are downloading (unable to access). Wouldn't the XML format from uniref90 have the GO Terms already?

I am new to the protein space so feel free to correct me if any of my assumptions are incorrect!

Thank you very much!

**Comment by nadavbra** [comment]
Have you checked out Issue https://github.com/nadavbra/protein_bert/issues/39?
I don't remember exactly the reasoning for using both the XML and FASTA files, I suppose it has to do with using these files for different stages of the preprocessing (with the FASTA being much more efficient to access in real time). In the end, it's mostly a matter of convenience when parsing data and there are many ways to do these operations. 
Good luck!

**Comment by dhui-nvidia** [comment]
Ah I see, thank you!
