### ISSUE TITLE
New Machine, New Conda Env, Same Error:

### ISSUE THREAD

**Issue by williamtbarker** [nadavbra/protein_bert#63]
[2023_07_31-19:53:28] Training set: Filtered out 0 of 45 (0.0%) records of lengths exceeding 798.
[2023_07_31-19:53:28] Validation set: Filtered out 0 of 6 (0.0%) records of lengths exceeding 798.
[2023_07_31-19:53:28] Training with frozen pretrained layers...
WARNING:absl:`lr` is deprecated in Keras optimizer, please use `learning_rate` or use the legacy optimizer, e.g.,tf.keras.optimizers.legacy.Adam.
Epoch 1/40
2/2 [==============================] - ETA: 0s - loss: 1.3525 WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 19s 5s/step - loss: 1.3525 - val_loss: 0.5438 - lr: 0.0100
Epoch 2/40
2/2 [==============================] - ETA: 0s - loss: 0.9588WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 4s 2s/step - loss: 0.9588 - val_loss: 0.3230 - lr: 0.0100
Epoch 3/40
2/2 [==============================] - ETA: 0s - loss: 0.6870WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 4s 2s/step - loss: 0.6870 - val_loss: 0.1695 - lr: 0.0100
Epoch 4/40
2/2 [==============================] - ETA: 0s - loss: 0.4762WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 6s 2s/step - loss: 0.4762 - val_loss: 0.0793 - lr: 0.0100
Epoch 5/40
2/2 [==============================] - ETA: 0s - loss: 0.3447WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
2/2 [==============================] - 5s 2s/step - loss: 0.3447 - val_loss: 0.0431 - lr: 0.0100
Epoch 6/40
2/2 [==============================] - ETA: 0s - loss: 0.2725WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

Epoch 6: ReduceLROnPlateau reducing learning rate to 0.0024999999441206455.
2/2 [==============================] - 4s 2s/step - loss: 0.2725 - val_loss: 0.0477 - lr: 0.0100
Epoch 7/40
2/2 [==============================] - ETA: 0s - loss: 0.2449WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.
WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0006249999860301614.
2/2 [==============================] - 5s 2s/step - loss: 0.2449 - val_loss: 0.0531 - lr: 0.0025
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 44
     40 model_generator = FinetuningModelGenerator(pretrained_model_generator, output_spec,
     41                                            dropout_rate=settings['dropout_rate'])
     43 # Fine-tune the model on your data
---> 44 finetune(
     45     model_generator, input_encoder, output_spec,
     46     train_data['seq'], train_data['label'], valid_data['seq'], valid_data['label'],
     47     seq_len=settings['seq_len'], batch_size=settings['batch_size'],
     48     max_epochs_per_stage=settings['max_epochs_per_stage'],
     49     lr=settings['initial_lr_with_all_layers'], begin_with_frozen_pretrained_layers=True,
     50     lr_with_frozen_pretrained_layers=settings['initial_lr_with_frozen_pretrained_layers'], n_final_epochs=1,
     51     final_seq_len=settings['final_epoch_seq_len'],
     52     final_lr=settings['final_epoch_lr'], callbacks=settings['training_callbacks']
     53 )
     55 seq = 'MKAILVVLLYTFTTANADTLCIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGKCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSNKGVTAACPHAGAKSFYKNLIWLVKKGNSYPKLNQTYINDKGKEVLVLWGIHHPPTTADQQSLYQNADAYVFVGTSRYSKKFKPEIATRPKVRDQEGRMNYYWTLVEPGDKITFEATGNLVVPRYAFTMERBAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNVHPITIGKCPKYVKSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLESTRIYQILAIYSTVASSLVLVVSLGAISFWMCSNGSLQCRICI'
     56 seq_len = len(seq) + 2

File ~\AppData\Local\anaconda3\Lib\site-packages\proteinbert\finetuning.py:52, in finetune(model_generator, input_encoder, output_spec, train_seqs, train_raw_Y, valid_seqs, valid_raw_Y, seq_len, batch_size, max_epochs_per_stage, lr, begin_with_frozen_pretrained_layers, lr_with_frozen_pretrained_layers, n_final_epochs, final_seq_len, final_lr, callbacks)
     50 if begin_with_frozen_pretrained_layers:
     51     log('Training with frozen pretrained layers...')
---> 52     model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr_with_frozen_pretrained_layers, \
     53             callbacks = callbacks, freeze_pretrained_layers = True)
     55 log('Training the entire fine-tuned model...')
     56 model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr, callbacks = callbacks, \
     57         freeze_pretrained_layers = False)

File ~\AppData\Local\anaconda3\Lib\site-packages\proteinbert\model_generation.py:31, in ModelGenerator.train(self, encoded_train_set, encoded_valid_set, seq_len, batch_size, n_epochs, lr, callbacks, **create_model_kwargs)
     27     model.optimizer.lr = lr
     29 model.fit(train_X, train_Y, sample_weight = train_sample_weigths, batch_size = batch_size, epochs = n_epochs, validation_data = encoded_valid_set, \
     30         callbacks = callbacks)
---> 31 self.update_state(model)

File ~\AppData\Local\anaconda3\Lib\site-packages\proteinbert\model_generation.py:35, in ModelGenerator.update_state(self, model)
     33 def update_state(self, model):
     34     self.model_weights = copy_weights(model.get_weights())
---> 35     self.optimizer_weights = copy_weights(model.optimizer.get_weights())

AttributeError: 'Adam' object has no attribute 'get_weights'

**Comment by williamtbarker** [comment]
I installed protein-bert through pip install, if it is still a keras version problem, any guesses on a stable version to revert to?

**Comment by williamtbarker** [comment]
Thanks for the suggestion. Unfortunately I'm locked down on this machine and cannot install git. Unless I can reinstall and fix this by pip I'm SOL correct?

**Comment by r-kellerm** [comment]
@williamtbarker - Could you please attach the updated stack trace? The latest code in git doesn't have `get_weights` call, as you can see in the code [here].
Maybe you can try git clone + `python setup.py build install` from protein_bert's main directory?
(https://github.com/nadavbra/protein_bert/blob/548e08f0a3df210e1a967d62e298c0334d9a7b5e/proteinbert/model_generation.py#L35).

**Comment by williamtbarker** [comment]
Here is the stack trace, I'm sure I'm wearing the Dunce Hat here, thanks in advance:

Epoch 7: ReduceLROnPlateau reducing learning rate to 0.0006249999860301614.
2/2 [==============================] - 5s 2s/step - loss: 0.1983 - val_loss: 0.0701 - lr: 0.0025
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 44
     40 model_generator = FinetuningModelGenerator(pretrained_model_generator, output_spec,
     41                                            dropout_rate=settings['dropout_rate'])
     43 # Fine-tune the model on your data
---> 44 finetune(
     45     model_generator, input_encoder, output_spec,
     46     train_data['seq'], train_data['label'], valid_data['seq'], valid_data['label'],
     47     seq_len=settings['seq_len'], batch_size=settings['batch_size'],
     48     max_epochs_per_stage=settings['max_epochs_per_stage'],
     49     lr=settings['initial_lr_with_all_layers'], begin_with_frozen_pretrained_layers=True,
     50     lr_with_frozen_pretrained_layers=settings['initial_lr_with_frozen_pretrained_layers'], n_final_epochs=1,
     51     final_seq_len=settings['final_epoch_seq_len'],
     52     final_lr=settings['final_epoch_lr'], callbacks=settings['training_callbacks']
     53 )
     55 seq = 'MKAILVVLLYTFTTANADTLCIGYHANNSTDTVDTVLEKNVTVTHSVNLLEDKHNGKLCKLRGVAPLHLGKCNIAGWILGNPECESLSTARSWSYIVETSNSDNGTCYPGDFINYEELREQLSSVSSFERFEIFPKTSSWPNHDSNKGVTAACPHAGAKSFYKNLIWLVKKGNSYPKLNQTYINDKGKEVLVLWGIHHPPTTADQQSLYQNADAYVFVGTSRYSKKFKPEIATRPKVRDQEGRMNYYWTLVEPGDKITFEATGNLVVPRYAFTMERBAGSGIIISDTPVHDCNTTCQTPEGAINTSLPFQNVHPITIGKCPKYVKSTKLRLATGLRNVPSIQSRGLFGAIAGFIEGGWTGMVDGWYGYHHQNEQGSGYAADLKSTQNAIDKITNKVNSVIEKMNTQFTAVGKEFNHLEKRIENLNKKVDDGFLDIWTYNAELLVLLENERTLDYHDSNVKNLYEKVRNQLKNNAKEIGNGCFEFYHKCDNTCMESVKNGTYDYPKYSEEAKLNREKIDGVKLESTRIYQILAIYSTVASSLVLVVSLGAISFWMCSNGSLQCRICI'
     56 seq_len = len(seq) + 2

File ~\AppData\Local\anaconda3\Lib\site-packages\proteinbert\finetuning.py:52, in finetune(model_generator, input_encoder, output_spec, train_seqs, train_raw_Y, valid_seqs, valid_raw_Y, seq_len, batch_size, max_epochs_per_stage, lr, begin_with_frozen_pretrained_layers, lr_with_frozen_pretrained_layers, n_final_epochs, final_seq_len, final_lr, callbacks)
     50 if begin_with_frozen_pretrained_layers:
     51     log('Training with frozen pretrained layers...')
---> 52     model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr_with_frozen_pretrained_layers, \
     53             callbacks = callbacks, freeze_pretrained_layers = True)
     55 log('Training the entire fine-tuned model...')
     56 model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr, callbacks = callbacks, \
     57         freeze_pretrained_layers = False)

File ~\AppData\Local\anaconda3\Lib\site-packages\proteinbert\model_generation.py:31, in ModelGenerator.train(self, encoded_train_set, encoded_valid_set, seq_len, batch_size, n_epochs, lr, callbacks, **create_model_kwargs)
     27     model.optimizer.lr = lr
     29 model.fit(train_X, train_Y, sample_weight = train_sample_weigths, batch_size = batch_size, epochs = n_epochs, validation_data = encoded_valid_set, \
     30         callbacks = callbacks)
---> 31 self.update_state(model)

File ~\AppData\Local\anaconda3\Lib\site-packages\proteinbert\model_generation.py:35, in ModelGenerator.update_state(self, model)
     33 def update_state(self, model):
     34     self.model_weights = copy_weights(model.get_weights())
---> 35     self.optimizer_weights = copy_weights(model.optimizer.get_weights())

AttributeError: 'Adam' object has no attribute 'get_weights'

**Comment by williamtbarker** [comment]
For future: I had to pip uninstall from (base) and then pip install git+https://github.com/nadavbra/protein_bert.git and now have this working on Jupyter.
