### ISSUE TITLE
'Adam' object has no attribute 'get_weights'

### ISSUE THREAD

**Issue by Chinjuj2017** [nadavbra/protein_bert#64]
Hi can you help,me to resolve this error
.

467/468 [============================>.] - ETA: 0s - loss: 0.0938WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

WARNING:tensorflow:`evaluate()` received a value for `sample_weight`, but `weighted_metrics` were not provided.  Did you mean to pass metrics to `weighted_metrics` in `compile()`?  If this is intentional you can pass `weighted_metrics=[]` to `compile()` in order to silence this warning.

468/468 [==============================] - 203s 421ms/step - loss: 0.0939 - val_loss: 0.0759 - lr: 0.0100

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[28], line 46
     38 model_generator = FinetuningModelGenerator(pretrained_model_generator, OUTPUT_SPEC, pretraining_model_manipulation_function = \
     39         get_model_with_hidden_layers_as_outputs, dropout_rate = 0.5)
     41 training_callbacks = [
     42     keras.callbacks.ReduceLROnPlateau(patience = 1, factor = 0.25, min_lr = 1e-05, verbose = 1),
     43     keras.callbacks.EarlyStopping(patience = 2, restore_best_weights = True),
     44 ]
---> 46 finetune(model_generator, input_encoder, OUTPUT_SPEC, train_set['seq'], train_set['label'], valid_set['seq'], valid_set['label'], \
     47         seq_len = 512, batch_size = 32, max_epochs_per_stage = 1, lr= 1e-04, begin_with_frozen_pretrained_layers = True, \
     48         lr_with_frozen_pretrained_layers = 1e-02, n_final_epochs = 1, final_seq_len = 1024, final_lr = 1e-05, callbacks = training_callbacks)
     51 # Evaluating the performance on the test-set
     53 results, confusion_matrix = evaluate_by_len(model_generator, input_encoder, OUTPUT_SPEC, test_set['seq'], test_set['label'], \
     54         start_seq_len = 512, start_batch_size = 32)

File ~/.local/lib/python3.8/site-packages/proteinbert/finetuning.py:52, in finetune(model_generator, input_encoder, output_spec, train_seqs, train_raw_Y, valid_seqs, valid_raw_Y, seq_len, batch_size, max_epochs_per_stage, lr, begin_with_frozen_pretrained_layers, lr_with_frozen_pretrained_layers, n_final_epochs, final_seq_len, final_lr, callbacks)
     50 if begin_with_frozen_pretrained_layers:
     51     log('Training with frozen pretrained layers...')
---> 52     model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr_with_frozen_pretrained_layers, \
     53             callbacks = callbacks, freeze_pretrained_layers = True)
     55 log('Training the entire fine-tuned model...')
     56 model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr, callbacks = callbacks, \
     57         freeze_pretrained_layers = False)

File ~/.local/lib/python3.8/site-packages/proteinbert/model_generation.py:31, in ModelGenerator.train(self, encoded_train_set, encoded_valid_set, seq_len, batch_size, n_epochs, lr, callbacks, **create_model_kwargs)
     27     model.optimizer.lr = lr
     29 model.fit(train_X, train_Y, sample_weight = train_sample_weigths, batch_size = batch_size, epochs = n_epochs, validation_data = encoded_valid_set, \
     30         callbacks = callbacks)
---> 31 self.update_state(model)

File ~/.local/lib/python3.8/site-packages/proteinbert/model_generation.py:35, in ModelGenerator.update_state(self, model)
     33 def update_state(self, model):
     34     self.model_weights = copy_weights(model.get_weights())
---> 35     self.optimizer_weights = copy_weights(model.optimizer.get_weights())

AttributeError: 'Adam' object has no attribute 'get_weights

_Originally posted by @Chinjuj2017 in https://github.com/nadavbra/protein_bert/issues/56#issuecomment-1711450651_

**Comment by r-kellerm** [comment]
@Chinjuj2017 - Try uninstalling the existing protein_bert package and reinstall from git, as described in [this](https://github.com/nadavbra/protein_bert/issues/63#issuecomment-1661152569) issue.
` pip install --force-reinstall git+https://github.com/nadavbra/protein_bert.git`

**Comment by Chinjuj2017** [comment]
It is working now..Thanks
