### ISSUE TITLE
Help with Embedding Aspect

### ISSUE THREAD

**Issue by ZakiaSalod** [nadavbra/protein_bert#67]
Hi ProteinBERT Team,

Hope you are well.

I am Zakia Salod, from South Africa.

Please kindly assist with the below:

1. My training set has max sequence length as 6685. And reading through the answers you posted here by @nadavbra: https://github.com/nadavbra/protein_bert/issues/1  you mentioned: "Ok I realized what your problem is: you provided some sequences of lengths that exceed the seq_len you provided (512). When you encode sequences, you need to use a seq_len that is at least (L + 2), where L is the longest sequence you provide." So, when I am trying to generate the embeddings using ProteinBERT, should the seq_len be set to 6687? As in, 6685+2=6687? 
2. In view of the above question, would this mean that using this trained model later, for predictions, then users can only input maximum sequence size as 6687? And if they need to input a sequence higher than this length, what is your advice for that? Should my system have a restriction in the front-end to say only sequence length 6687 is allowed? Or, would ProteinBERT pad the parts of the sequence > length of 6687 and then perform the inference? Please help.

Thanks in advance. Much appreciated.
Kind Regards,
Zakia Salod

**Comment by ZakiaSalod** [comment]
Also, please help with the following:

1. In this code, for example: `train_encoded_x = input_encoder.encode_X(train_set['protein_seq'].values, seq_len)
train_local_representations, train_global_representations = model.predict(train_encoded_x, batch_size=batch_size)`

Which variable from here (embedding) should be used as features to train a model using standard machine learning algorithms - am I correct to say that it should be: train_global_representations  since this would have the embedding for the whole protein sequence?

**Comment by ZakiaSalod** [comment]
I am now using seq_len as 3951, (max length + 2), after I random sampled my initial dataset. I am running this on Kaggle to get the embeddings, but my code: `train_encoded_x = input_encoder.encode_X(train_set['protein_seq'].values, seq_len)
train_local_representations, train_global_representations = model.predict(train_encoded_x, batch_size=batch_size)`  results in the following: "Your notebook tried to allocate more memory than is available. It has restarted." using Kaggle's GPU P100 - please kindly advise? Much appreciated, in advance.

**Comment by nadavbra** [comment]
1. Yes, use L+2 for seq_len, i.e. 6687 in your case.
2. You can later use a larger seq_len if you need to process even longer sequences, ProteinBERT can handle it. Shorter sequences will be padded if you use a seq_len that is larger than the actual lengths. You can also initiate a different model with exactly the right seq_len for each protein sequence, but that will be less compute efficient.
3. If you want to learn something about the protein as a whole, use the global embeddings as features.
4. It looks like a RAM problem of your machine, not the GPU.
