### ISSUE TITLE
import proteinbert error 

### ISSUE THREAD

**Issue by anonimoustt** [nadavbra/protein_bert#68]
Hi,

I was trying to run the code of demo code. However I am getting module not found error at:

from proteinbert import OutputType, OutputSpec, FinetuningModelGenerator, load_pretrained_model, finetune, evaluate_by_len
from proteinbert.conv_and_global_attention_model import get_model_with_hidden_layers_as_outputs

Further, I am also getting following error

![image](https://github.com/nadavbra/protein_bert/assets/134943795/cc244573-0fbf-4a30-9a87-6540862359c2)

Any Suggestion?

**Comment by nadavbra** [comment]
Looks like the model pkl file is not downloaded. Try to download it directly from the ftp site.
