### ISSUE TITLE
Model download error

### ISSUE THREAD

**Issue by Lychem** [nadavbra/protein_bert#69]
Hi @nadavbra,

I was trying to run the proteinbert demo script. However, I had an error when downloading the model pkl file. Do you have any ideas about this error?

```
$ wget ftp://ftp.cs.huji.ac.il/users/nadavb/protein_bert/epoch_92400_sample_23500000.pkl
--2023-11-09 11:17:29--  ftp://ftp.cs.huji.ac.il/users/nadavb/protein_bert/epoch_92400_sample_23500000.pkl
           => ‘epoch_92400_sample_23500000.pkl’
Resolving ftp.cs.huji.ac.il (ftp.cs.huji.ac.il)... 132.65.116.15
Connecting to ftp.cs.huji.ac.il (ftp.cs.huji.ac.il)|132.65.116.15|:21... connected.
Logging in as anonymous ... Logged in!
==> SYST ... done.    ==> PWD ... done.
==> TYPE I ... done.  ==> CWD (1) /users/nadavb/protein_bert ...
No such directory ‘users/nadavb/protein_bert’.
```

Best

**Comment by ddofer** [comment]
You can also download directly from Huggingface as a Keras model: https://huggingface.co/GrimSqueaker/proteinBERT

**Comment by Lychem** [comment]
I just tried the script again and it worked. Thank you for the reply.

**Comment by Yinlf1206** [comment]
@Lychem Hello, do you know how to load the model and could you tell me the code?

**Comment by ddofer** [comment]
> @Lychem Hello, do you know how to load the model and could you tell me the code?

1. Please open a new issue if needed.Please look ta the example code in /bin, and the example notebook:

https://github.com/nadavbra/protein_bert/blob/master/ProteinBERT%20demo.ipynb

**Comment by Yinlf1206** [comment]
> > @Lychem Hello, do you know how to load the model and could you tell me the code?
> 
> 1. Please open a new issue if needed.Please look ta the example code in /bin, and the example notebook:
> 
> https://github.com/nadavbra/protein_bert/blob/master/ProteinBERT%20demo.ipy

Thank you so much! I tried it again according this link and it worked.
