### ISSUE TITLE
Pretraining is better than FInetuning

### ISSUE THREAD

**Issue by cirdeCyL** [nadavbra/protein_bert#70]
Hi Nadav,

thank you for this BERT model.
I am currently trying to finetune this Transformer for a protein-protein interaction - like task. The input seqs have high similarity and I suspect that their global feature are also pretty much the same.

After finetuning with freezed weights except for the added last layer (+dropouts) and output layer, the pretrained representation (which was used further used in a ML ALg.) performed better than the finetuned representation.

I suspect, that the global representation is for my task not as interesting as the local representation.

I stumble upon the line 122 in proteinbert/model_generation.py. It's within the create function of the FinetuningModelGenerator class.
The finetuning task itself is a binary classification and not a seq, so the var last_hidden_layer will be the global representation. Therefore, I do not optimize the local representation for this task. 

What would you suggest, in order to finetune this on the local representation. Can I just removed the Condition in line 122 and hard code pretraining_output_seq_layer, or will this be a problem.

Could you also shed some light on why you have added the conditional clause?

Cheers,
Cedric

**Comment by cirdeCyL** [comment]
Hello,

Following your previous feedback, I conducted an in-depth comparison between pretrained local representations (post-flattening) and finetuned global representations using a single layer. I utilized the get_model_with_hidden_layer_as_outputs for the latter.

Even after employing early stopping during the finetuning process, the pretrained local representations consistently outperform the finetuned global representations. This outcome suggests a significant potential benefit in enabling finetuning specifically on the local representation for binary classification tasks. This becomes especially crucial if we intend to maintain frozen weights for a majority of the model, including the global attention block.

It's important to note that the proteins under examination exhibit diverse structural features while maintaining a consistent overall functionality.

I believe allowing the flexibility to finetune local representations could lead to substantial improvements in our classification tasks, leveraging the varied protein structures while preserving their shared functional characteristics.

Your insights on this matter would be greatly appreciated.

Thank you for your attention and consideration.

**Comment by nadavbra** [comment]
@cirdeCyL 
If you unfreeze the model weights, then fine-tuning on a global outcome will also optimize the local representations of hidden layers (which feed into the global outcome). I'd consider allowing the model train for a while with frozen hidden layers, and then unfreeze those layers and let the model train from end to end.
Of course, what works best is task and dataset specific, and the ultimate arbiter in these matters should be your empirical results.

**Comment by cirdeCyL** [comment]
Ok, I will try out different scenarios.

- finetune only freeze (1layer) on global
- finetune only freeze (1layer) on local
- finetune like described in paper on global -> use local/global for the task later on
- finetune like described in paper on local -> use local for the task

Thank you for the help. I'll close the issue, but will post the results later.
