### ISSUE TITLE
Annotated data Request

### ISSUE THREAD

**Issue by Macaulay001** [nadavbra/protein_bert#71]
Dear Dr. Brandes, Dr. Ofer, and Dr. Linial,

While the datasets for the downstream tasks are available here, I noticed that the proteins are represented by amino acid sequences rather than protein names. 
I am reaching out to inquire if there is any possibility of obtaining these datasets with protein names instead of amino acid sequences. Having the datasets in a more interpretable format would greatly help.

Thanks in anticipation.

**Comment by ddofer** [comment]
Hi, Those are from an external benchmark, tape. 
The fluorescence and thermostability dataset includes mutants which may lack a uniprotKB ID. I suggest checking the papers tape got them from for the name of the "core" /WT sequence. 

Good luck! 


@article{sarkisyan2016,
  title={Local fitness landscape of the green fluorescent protein},
  author={Sarkisyan, Karen S and Bolotin, Dmitry A and Meer, Margarita V and Usmanova, Dinara R and Mishin, Alexander S and Sharonov, George V and Ivankov, Dmitry N and Bozhanova, Nina G and Baranov, Mikhail S and Soylemez, Onuralp and others},
  journal={Nature},
  volume={533},
  number={7603},
  pages={397},
  year={2016},
  publisher={Nature Publishing Group}
}

@article{rocklin2017,
  title={Global analysis of protein folding using massively parallel design, synthesis, and testing},
  author={Rocklin, Gabriel J and Chidyausiku, Tamuka M and Goreshnik, Inna and Ford, Alex and Houliston, Scott and Lemak, Alexander and Carter, Lauren and Ravichandran, Rashmi and Mulligan, Vikram K and Chevalier, Aaron and others},
  journal={Science},
  volume={357},
  number={6347},
  pages={168--175},
  year={2017},
  publisher={American Association for the Advancement of Science}
}
