### ISSUE TITLE
Dead Link - CAFA 4

### ISSUE THREAD

**Issue by BenjyNStrauss** [nadavbra/protein_bert#73]
(Apologies if this is a duplicate – I didn't see this asked)

The download link for the GO annotations: https://www.biofunctionprediction.org/cafa-targets/cafa4ontologies.zip no longer works, and it goes to a "no results found" page.  Where can I download the file from?

Thank you,
Benjamin Strauss

**Comment by nadavbra** [comment]
See https://github.com/nadavbra/protein_bert/issues/39 and https://github.com/nadavbra/protein_bert/issues/61
