### ISSUE TITLE
Log directory content required for running -final papper analyses.ipynb

### ISSUE THREAD

**Issue by AdilNomali** [nadavbra/protein_bert#74]
Hi ProteinBERT Team,

Hope you are well.

I am Adil Hassan, from Pakistan.

Please kindly assist with the below:
while runing file in colab: bin/ProteinBERT - final paper analyses.ipynb the content of '/cs/phd/nadavb/logs/slurm_jobs/finetuning_from_different_pretraining_snapshots/' and nadavb/proteinbert_project/data/ directories are missing.. could any on provide the mentioned  directories content as .zip please.

Thanks in advance. Much appreciated.
Kind Regards,
Adil Hassan
#nadavbra

**Comment by nadavbra** [comment]
Are you referring to the ftp site? We moved its content elsewhere (see recent changes and new instructions in the README and updated notebook).
