### ISSUE TITLE
Original h5 file

### ISSUE THREAD

**Issue by BenjyNStrauss** [nadavbra/protein_bert#78]
Hello,

I'm trying to write my own .h5 file generator to work with a modified version of proteinbert.(modifications to the language/amino acids used).  Could you supply the header and first few lines of your original .h5 file so I can write my own generator?  (I hope this isn't asking too much)

Due to the dead link in #39 , I'm unable to generate an .h5 file using your method.  I looked at the GO site, but I am unsure how to process the data properly as I'm not sure of the target format.

Thank you,
Benjamin Strauss

**Comment by nadavbra** [comment]
@BenjyNStrauss I've already left the Hebrew University of Jerusalem where I created ProteinBERT and have this h5 file, so I don't have access to it anymore. The h5 format doesn't quite have headers; it has various datasets (kind of like SQL tables). Our specific h5 file has the following datasets: `included_annotations`, `uniprot_ids`, `seqs`, `seq_lengths `and `annotation_masks`. You can learn more about the format of the h5 file by looking at the `create_h5_dataset` function that creates it (in https://github.com/nadavbra/protein_bert/blob/master/proteinbert/uniref_dataset.py).

**Comment by BenjyNStrauss** [comment]
Thank you so much.  ('ll try to get more info on the h5 file's format generically).

I'm not too good with reading through python, but if I am understanding you correctly, you have a uniprot_id, and the corresponding sequence, sequence length, it's go_annotation number, and whether the annotation was masked from the training process.

Which column(s) were the keys?  Or does it not matter.
Thanks again,
-BNS

**Comment by nadavbra** [comment]
The h5 format doesn't quite have a key, just a bunch of datasets.
The `annotation_masks`, if I remember correctly, just indicates whether each GO annotation is associated with each protein (it's a boolean matrix). The annotations that are actually used during the pretraining are determined on the fly.

**Comment by BenjyNStrauss** [comment]
Thanks for clarifying about the keys; it means ChatGPT lied to me.

Just 1 more question (hopefully):
• Is the boolean matrix with 'shape = (n_seqs, len(common_annotation_ids))' organized 'len(common_annotation_ids)' per line and n_seqs lines or vice versa.

Thank you once again.

**Comment by BenjyNStrauss** [comment]
Actually, nevermind, I figured it out looking at the python code.  It seems I misunderstood how H5 actually worked, among other things
