### ISSUE TITLE
cannot load pkl when loading the pre-trained protein_bert model

### ISSUE THREAD

**Issue by WilliamSawran** [nadavbra/protein_bert#8]
Hi nadavbra,

I'm running into the same issue as WangShixianChina (commented on Sep 29). When I try to load the pret-rained model in my protein_bert.py script:

________________________________________________________________________
from tensorflow import keras
from proteinbert import OutputType, OutputSpec, FinetuningModelGenerator, load_pretrained_model, finetune, evaluate_by_len
from proteinbert.conv_and_global_attention_model import get_model_with_hidden_layers_as_outputs

pretrained_model_generator, input_encoder = load_pretrained_model()
________________________________________________________________________

I get an error message stating: pickle.UnpicklingError: pickle data was truncated.

I need help unloading/unpickling  the epoch_92400_sample_23500000.pkl file. I tried to install the exact or closest Python packages required by ProteinBERT.  I also show the stack trace when I try to load the pretrained model (see below).
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
$ pip install tensorflow==2.4.0
Collecting tensorflow==2.4.0
Successfully installed gast-0.3.3 grpcio-1.32.0 numpy-1.19.5 tensorflow-2.4.0 tensorflow-estimator-2.4.0

$ pip install tensorflow_addons==0.12.1
Successfully installed  tensorflow_addons==0.12.1

$ pip install numpy==1.20.1
ERROR: Could not find a version that satisfies the requirement numpy==1.20.1 (from versions: 1.3.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.8.1, 1.8.2, 1.9.0, 1.9.1, 1.9.2, 1.9.3, 1.10.0.post2, 1.10.1, 1.10.2, 1.10.4, 1.11.0, 1.11.1, 1.11.2, 1.11.3, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0, 1.13.1, 1.13.3, 1.14.0rc1, 1.14.0, 1.14.1, 1.14.2, 1.14.3, 1.14.4, 1.14.5, 1.14.6, 1.15.0rc1, 1.15.0rc2, 1.15.0, 1.15.1, 1.15.2, 1.15.3, 1.15.4, 1.16.0rc1, 1.16.0rc2, 1.16.0, 1.16.1, 1.16.2, 1.16.3, 1.16.4, 1.16.5, 1.16.6, 1.17.0rc1, 1.17.0rc2, 1.17.0, 1.17.1, 1.17.2, 1.17.3, 1.17.4, 1.17.5, 1.18.0rc1, 1.18.0, 1.18.1, 1.18.2, 1.18.3, 1.18.4, 1.18.5, 1.19.0rc1, 1.19.0rc2, 1.19.0, 1.19.1, 1.19.2, 1.19.3, 1.19.4, 1.19.5)
ERROR: No matching distribution found for numpy==1.20.1
$ pip install numpy==1.19.5
Requirement already satisfied: numpy==1.19.5

$ pip install pandas==1.2.3
ERROR: Could not find a version that satisfies the requirement pandas==1.2.3 (from versions: 0.1, 0.2, 0.3.0, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.6.0, 0.6.1, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.9.0, 0.9.1, 0.10.0, 0.10.1, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.15.0, 0.15.1, 0.15.2, 0.16.0, 0.16.1, 0.16.2, 0.17.0, 0.17.1, 0.18.0, 0.18.1, 0.19.0, 0.19.1, 0.19.2, 0.20.0, 0.20.1, 0.20.2, 0.20.3, 0.21.0, 0.21.1, 0.22.0, 0.23.0, 0.23.1, 0.23.2, 0.23.3, 0.23.4, 0.24.0, 0.24.1, 0.24.2, 0.25.0, 0.25.1, 0.25.2, 0.25.3, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5)
ERROR: No matching distribution found for pandas==1.2.3
$ pip install pandas==1.1.5
Successfully installed pandas-1.1.5

$ pip install h5py==3.2.1
ERROR: Could not find a version that satisfies the requirement h5py==3.2.1 (from versions: 2.2.1, 2.3.0b1, 2.3.0, 2.3.1, 2.4.0b1, 2.4.0, 2.5.0, 2.6.0, 2.7.0rc2, 2.7.0, 2.7.1, 2.8.0rc1, 2.8.0, 2.9.0rc1, 2.9.0, 2.10.0, 3.0.0rc1, 3.0.0, 3.1.0)
ERROR: No matching distribution found for h5py==3.2.1
$ pip install h5py==3.1.0
Successfully installed cached-property-1.5.2 h5py-3.1.0

$ pip install lxml==4.3.2
Successfully installed lxml-4.3.2

$ pip install pyfaidx==0.5.8
Successfully installed pyfaidx-0.5.8

$ python protein_bert.py 
2021-12-02 08:33:15.585243: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-12-02 08:33:15.585275: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "protein_bert.py", line 40, in <module>
    pretrained_model_generator, input_encoder = load_pretrained_model()
  File "/home/williamsawran/anaconda3/envs/protein_bert/lib/python3.6/site-packages/proteinbert/existing_model_loading.py", line 53, in load_pretrained_model
    other_optimizer_kwargs = other_optimizer_kwargs, annots_loss_weight = annots_loss_weight, load_optimizer_weights = load_optimizer_weights)
  File "/home/williamsawran/anaconda3/envs/protein_bert/lib/python3.6/site-packages/proteinbert/model_generation.py", line 159, in load_pretrained_model_from_dump
    n_annotations, model_weights, optimizer_weights = pickle.load(f)
_pickle.UnpicklingError: pickle data was truncated

**Comment by nadavbra** [comment]
Hi @WilliamSawran ,

I want to start by making sure that you got the file ~/proteinbert_models/epoch_92400_sample_23500000.pkl in order.

What is the size of this file?

You can run `ls -lh  /proteinbert_models/epoch_92400_sample_23500000.pkl`

**Comment by WilliamSawran** [comment]
Hi Nadavrbra,

FileZilla reported that the pkl file was transferred from your server to my local machine successfully. I trusted FileZilla and naively proceeded to run the protein_bert code.  However, the size between my transferred pkl file (30MB) and your pkl file (187MB) was not the same. A colleague of mine was able to transfer for me your entire pkl file and I was able to load the pre-trained proteinbert model. 

Sorry for any inconvenience and thank you for answering my message. I appreciate the prompt reply, especially since past researchers I've contacted via email don't respond at all. I was able to obtain the pkl file and load the pre-trained proteinbert model, so you can close this case.

**Comment by nadavbra** [comment]
I'm glad I could help. Good luck using the model!
