### ISSUE TITLE
KeyError: "Unable to open object (object 'test_set_mask' doesn't exist)"

### ISSUE THREAD

**Issue by BenjyNStrauss** [nadavbra/protein_bert#81]
Apologies if this is a stupid question, but I'm trying to train ProteinBert and I keep getting the error included below.

I used a custom dataset, which I needed a custom reader+h5.writer for (which is attached).  I'm not sure what's going wrong as I didn't see any mention of 'test_set_mask' in the original h5 writer.  I'm using an unusual token format (and I need to re-do the tokenizer), though this doesn't seem to be related to the tokenizer, hence my confusion.

Please help, and thank you!

Traceback (most recent call last):
  File "…/proteinBERT/pretrain_proteinbert_sp.py", line 109, in <module>
    run_pretraining(create_model_function, epoch_generator, args.dataset_file, create_model_kwargs = create_model_kwargs, optimizer_class = optimizer_class, lr = args.lr, \
  File "…/proteinBERT/pretraining.py", line 48, in run_pretraining
    model_trainer.setup(DatasetHandler(h5f), resume_from = resume_from)
  File "…/proteinBERT/pretraining.py", line 81, in setup
    starting_episode = self.epoch_generator.setup(dataset_handler, start_sample_index)
  File "…/proteinBERT/pretraining.py", line 142, in setup
    self._load_chunk()
  File "…/proteinBERT/pretraining.py", line 183, in _load_chunk
    chunk_sample_cache = self.dataset_handler[self.current_sample_index:(self.current_sample_index + self.load_chunk_size)]
  File "…/proteinBERT/pretraining.py", line 304, in __getitem__
    self.dataset_h5f['test_set_mask'][slicing])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/bns/Library/Python/3.9/lib/python/site-packages/h5py/_hl/group.py", line 357, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 189, in h5py.h5o.open
KeyError: "Unable to open object (object 'test_set_mask' doesn't exist)"
[swipred_dataset.txt](https://github.com/nadavbra/protein_bert/files/14132289/swipred_dataset.txt)

**Comment by nadavbra** [comment]
If your custom dataset doesn't need a separate test set, you can set the `test_set_mask` to be an all-false boolean vector.

**Comment by BenjyNStrauss** [comment]
Thanks you.  I'm still a little confused though.  Does ProteinBERT expect a separate test set in the .h5 file?  I thought ProteinBERT, split the training data itself into a learning and test set.

**Comment by nadavbra** [comment]
You can definitely train it without a test set (with an all-false vector). If you only train it on sequences, everything should be fine. But if you also train it on GO annotations, you should be worried about information leakage between this training and your final application/benchmark. That's why we included a test set in our original work - we removed any protein within a sequence identity cutoff from all the proteins we used for evaluation in our benchmarks.

**Comment by BenjyNStrauss** [comment]
Thanks for your reply, that helps me straighten some things out.  Unfortunately, I'm still a little confused when it comes to:

(1) What I'm trying to do is to predict GO annotations from sequence – does that mean I'm training it on GO annotations?  If not, what is the difference?

(2) Does this all-false vector for ```test_set_mask``` need to be of a certain length?

(3) Where does it write the test set into the .h5 file.  The code of create_h5_dataset doesn't seem to have this ability.

Thanks again in advance, and apologies for continuing to take your time.

**Comment by nadavbra** [comment]
1) If you want to predict GO annotations, it would make sense to pretrain ProteinBERT with GO annotations. Just make to designate a test set so you'd be able to rigorously evaluate GO annotation prediction.

2) It has to be the dataset size (i.e. the total number of proteins)

3) I don't remember exactly at what stage we did it. My colleague wrote the code for choosing the test set.

**Comment by BenjyNStrauss** [comment]
I see.  I think I missed a module.  On closer inspection, it's in "set_h5_testset.py", which didn't get copied to my system.  Thanks so much for all your help.
