### ISSUE TITLE
How to extract the embedding of an amino acid?

### ISSUE THREAD

**Issue by thnhan** [nadavbra/protein_bert#82]
@nadavbra Hi author,
I am interesting in your work, ProteinBERT, and I am attempting to use your model to embed an amino acid for the protein interaction prediction task.
I implemented a short program as below to generate 20 amino acid embeddings.
This program is worked, but I am not sure if it is the right way or not to get the embedding of each amino acid.
Could you kindly tell me how to use ProteinBERT to get pre-trained embeddings of amino acids? Thank you!

```
import numpy as np
from proteinbert import load_pretrained_model
from proteinbert.conv_and_global_attention_model import get_model_with_hidden_layers_as_outputs

aa = 'ARNDCQEGHILKMFPSTWYVOUBZXJ'  # amino acids
fixlen = len(aa)

pretrained_model_generator, input_encoder = load_pretrained_model(
    local_model_dump_dir=r"D:\protein_bert\protein_bert",
    local_model_dump_file_name='default.pkl',
    download_model_dump_if_not_exists=False)
protbert_model = get_model_with_hidden_layers_as_outputs(pretrained_model_generator.create_model(fixlen))

encoded_x = input_encoder.encode_X(protseq, fixlen)
local_representations, global_representations = protbert_model.predict(encoded_x, batch_size=1)

# ====== THIS IS embeddings of amino acid ======
aa_embeddings = np.array([np.sum(v, axis=0) for v in local_representations]) 
```

**Comment by nadavbra** [comment]
@thnhan Why do you want per-aa embeddings rather than embeddings for the entire protein sequences? ProteinBERT was not designed to embed individual amino acids.
If you really are interested in ProteinBERT amino-acid embeddings, I would try to get them from the first layer of the model (of type `keras.layers.Embedding`).

**Comment by thnhan** [comment]
@nadavbra Thank you for your help. 
I want per-aa embeddings because my model was designed to use amino acid embeddings through the Embedding layer (a keras layer of my model). 
After this Embedding layer, an entire fix-length protein sequence can be converted to embeddings and fed to MLPs. My model will need to further adjust the weights of that layer.

In practice, I also used the "global_representations" for my model but to use them I removed that layer from my model. I used the below codes, which are according to your github demo.
``` python
pretrained_model_generator, input_encoder = load_pretrained_model(
    local_model_dump_dir=r"D:\protein_bert\protein_bert",
    local_model_dump_file_name='default.pkl',
    download_model_dump_if_not_exists=False)
protbert_model = get_model_with_hidden_layers_as_outputs(pretrained_model_generator.create_model(fixlen))

encoded_x = input_encoder.encode_X(protseq, fixlen)
local_representations, global_representations = protbert_model.predict(encoded_x, batch_size=64)
```
Would you help me get per-aa embeddings? Or could you show me the codes to get them?
Thank you so much!

**Comment by nadavbra** [comment]
I will say again that it sounds like you should use the full embeddings of ProteinBERT (`local_representations` and `global_representations` in your above code) rather than just the per-amino-acid embeddings.

If you insist on using the amino-acid embeddings, you can extract them along these lines:
```python
embedding_layer = model.get_layer('embedding-seq-input')
aa_embeddings = embedding_layer.get_weights()[0]
```

`aa_embeddings` should be of shape `(vocab_size, d_hidden_seq)`.

**Comment by ddofer** [comment]
+ Question - are you looking for the embeddings of each individual AA (aka - just extract it from the embedding layer of the model), or the transformer model's embeddings of each position ? (For that- look at the position specific classificiation examples, e.g. secondary structure). 
But I agree with Nadav, naively, sounds like you may just want to use the full embeddings, the vocab/tokenizer is per AA, not multi-char, so it's small and easy to learn . (The position and contextual embeddings are where the real meat is)

**Comment by ddofer** [comment]
Nadav's solution will get you the per AA embedding matrix.

**Comment by thnhan** [comment]
> I will say again that it sounds like you should use the full embeddings of ProteinBERT (`local_representations` and `global_representations` in your above code) rather than just the per-amino-acid embeddings.
> 
> If you insist on using the amino-acid embeddings, you can extract them along these lines:
> 
> ```python
> embedding_layer = model.get_layer('embedding-seq-input')
> aa_embeddings = embedding_layer.get_weights()[0]
> ```
> 
> `aa_embeddings` should be of shape `(vocab_size, d_hidden_seq)`.

Thank you, @nadavbra and @ddofer so much,
I attempt to get the embedding of the entire protein sequence using the embeddings of amino acids in that protein sequence. I think your solution will help me a lot. My code about `local_representations` and `global_representations` is an example that I used to mine your model for my work.

I also consulted two additional threads "GO Annotation Vector #38" and "What to do with the local_representations and global_representations #6", to understand how to use "representations".
Kindly could I ask you two more questions?
1) Would you tell me, in order, which row does each amino acid correspond to in this matrix, `(vocab_size, d_hidden_seq)`? Or can I find this information in your paper?
2) `global_representations` vector that I am getting is of the size 15599, so how do I get the 8943-dimensional `global_representations` vector?

Thank you!

**Comment by thnhan** [comment]
Thank you, @nadavbra <https://github.com/nadavbra> and @ddofer
<https://github.com/ddofer> so much,
I attempt to get the embedding of the entire protein sequence using the
embeddings of amino acids in that protein sequence. I think your solution
will help me a lot. My code about local_representations and
global_representations is an example that I used to mine your model for my
work.

I also consulted two additional threads "GO Annotation Vector #38
<https://github.com/nadavbra/protein_bert/issues/38>" and "What to do with
the local_representations and global_representations #6
<https://github.com/nadavbra/protein_bert/issues/6>", to understand how to
use "representations".
Kindly could I ask you two more questions?

   1. Would you tell me, in order, which row each amino acid corresponds to
   in this matrix, (vocab_size, d_hidden_seq)? Or can I find this
   information in your paper?
   2. global_representations vector that I am getting is of the size 15599,
   so how do I get the 8943-dimensional global_representations vector?

Thank you!

**Comment by nadavbra** [comment]
1. In the `tokenization` submodule you can use the `token_to_index` and `index_to_token` dictionaries that map between token and token indices (rows in the tokem embedding matrix).
2. `global_representations` is of dimension 15599 because you used `get_model_with_hidden_layers_as_outputs`. If you don't use it you'll only get features from the output layer.

**Comment by thnhan** [comment]
> 1. In the `tokenization` submodule you can use the `token_to_index` and `index_to_token` dictionaries that map between token and token indices (rows in the tokem embedding matrix).
> 2. `global_representations` is of dimension 15599 because you used `get_model_with_hidden_layers_as_outputs`. If you don't use it you'll only get features from the output layer.

Thank you @nadavbra,
according to your solution, I have gotten the `aa_embedding` of size `(26,128)` and `global_representations` of dimension 8943.

1. I used the command `model = pretrained_model_generator.create_model(seq_len)` for `global_representations`
2. In the token sequence of the protein sequence, I removed its first and last tokens because they are not for amino acids.

Is my above usage exactly as you suggest?

Thank you!

**Comment by nadavbra** [comment]
Yes, that seems about right.
I will say that I expect the higher-dimensional `global_representations` (with `get_model_with_hidden_layers_as_outputs`) to be more useful for most tasks.

**Comment by thnhan** [comment]
> Yes, that seems about right. I will say that I expect the higher-dimensional `global_representations` (with `get_model_with_hidden_layers_as_outputs`) to be more useful for most tasks.

Thank you so much,
I will try to use both types of `global_representations`.
