### ISSUE TITLE
Running Benchmarks

### ISSUE THREAD

**Issue by BenjyNStrauss** [nadavbra/protein_bert#85]
I may have missed something, but I'm confused as to how benchmarks work?  Are they used to evaluate the trained model?  If so, what is the form of the output?

Also, the benchmarks seem to run indefinitely – is there a parameter I can set to prevent this (like with the training model)?

**Comment by nadavbra** [comment]
Each benchmarks evaluate trained models, each has a different output (as described in our paper).
You can find code for running them on our Jupyter notebook.

**Comment by BenjyNStrauss** [comment]
Thanks.

Thanks.  I think I'm doing something wrong though.  After running the notebook code the graph doesn't display in Eclipse's pyDev.  Is there a way to do this, and/or is there a way to make ProteinBERT spit out a ROC-AUC score?

(And it turned out that a couple of my problems were illusions, including the indefinite runtime – In case you might have noticed, python is not my primary programming language)

**Comment by r-kellerm** [comment]
Hi,

`evaluate_by_len` (and internally `get_evaluation_results`) already returns the ROC AUC score for binary classification tasks (as well as Spearman for numerical regression task and accuracy for multi-label classification task). It also optionally returns the confusion matrix for classification tasks. You may update the desired metrics in `get_evaluation_results` : https://github.com/nadavbra/protein_bert/blob/master/proteinbert/finetuning.py#L116

**Comment by BenjyNStrauss** [comment]
Thank you!  I don't know how I missed it.
