### ISSUE TITLE
Using vector representations in the "weights" parameter in the "embedding" section of an LSTM model after fine-tuning my own data

### ISSUE THREAD

**Issue by boncul** [nadavbra/protein_bert#87]
Hello dear @nadavbra,

We talked about ProteinBERT in another issue (https://github.com/nadavbra/protein_bert/issues/77). I solved the problem there, thank you. But now I have another problem.

I prepared all my protein data as in your sample benchmarks and fine-tuned them as you explained in the `Fine-tune the model for the signal peptide benchmark` block in `ProteinBERT Demo`. Later, when I wanted to run the `Prepare sequence embeddings from fine-tuned model` block, I first received the `seq_len is not defined` error. I set the `seq_len` value to `512` as in the first block to solve it. Later, when he asked me for the `seqs` variable, I assigned it as `seqs = test_set['seq']`. Here `ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (28994,) + inhomogeneous part.`. When I received the error, I gave it as `seqs = test_set['seq'][0]` to try first, and it solved the problem.

The problem is; How should I go about giving the sequences to the `weights` parameter in
```
model.add(Embedding(input_dim=vocab_size,
                    output_dim=embedding_size,
                    weights=[wv.vectors],
                    input_length=max_length,
                    mask_zero=False,
                    trainable=True))
```
instead of giving them one by one? After this layer, I will use a bidirectional LSTM model, and I want that model to work successfully.

I wrote a long text; please excuse me. Thank you very much in advance.

**Comment by nadavbra** [comment]
I guess this issue is no longer relevant.
If you want to re-open it, please try to be clearer about your specific ProteinBERT-related question.
