### ISSUE TITLE
Failing to extract global embedding (1,15599) -> (1,512) 

### ISSUE THREAD

**Issue by tomanci** [nadavbra/protein_bert#88]
Hi @nadavbra,
I'm attempting to use Protein Bert for a downstream task. In particular, I want to used the global embeddings to classify my amino acids sequences. 
 
I would like to have an embedding dimension for the global representation of 512 and I followed your steps on the Readme file on how to download the repo and the necessary packages but when I run these lines :

```
SEQ_LEN = 1026
amin_sq =["MKSPVLITGGLSFLLSACSGGGGGFDVDDVSNPSSSSKPRYQDDTS"] 
pretrained_model_generator, input_encoder = load_pretrained_model()
model = get_model_with_hidden_layers_as_outputs(pretrained_model_generator.create_model(SEQ_LEN))
encoded_x = input_encoder.encode_X(amin_sq, SEQ_LEN)
local_representations, global_representations = model.predict(encoded_x, batch_size=1)
 
print(local_representations.shape)
print(global_representations.shape)
```
I get as dimension for global_representation (1, 15599)
I had also a look at issues #1 and #82 but I still don't know what I am doing wrong.

I hope you can help me.

Thank you in advance, 
Tommaso

**Comment by nadavbra** [comment]
@tomanci You're using `get_model_with_hidden_layers_as_outputs` which gives you embeddings from hidden layers as well. This is probably desirable and I'd keep it for most downstream tasks.
