### ISSUE TITLE
What do the settings mean?

### ISSUE THREAD

**Issue by BenjyNStrauss** [nadavbra/protein_bert#89]
I'm looking at the settings: in [https://github.com/nadavbra/protein_bert/blob/master/ProteinBERT%20demo.ipynb](url) under "run all benchmarks", and I'm confused about what they all do.  Apologies if this is a duplicate.

```
settings = {
    'max_dataset_size': None,
    'max_epochs_per_stage': 40,
    'seq_len': 512,
    'batch_size': 32,
    'final_epoch_seq_len': 1024,
    'initial_lr_with_frozen_pretrained_layers': 1e-02,
    'initial_lr_with_all_layers': 1e-04,
    'final_epoch_lr': 1e-05,
    'dropout_rate': 0.5,
    'training_callbacks': [
        keras.callbacks.ReduceLROnPlateau(patience = 1, factor = 0.25, min_lr = 1e-05, verbose = 1),
        keras.callbacks.EarlyStopping(patience = 2, restore_best_weights = True),
    ],
}
```

What is max_epochs_per_stage?
What is a stage?
What is the purpose of fine-tuning an already-trained model?
And how does one alter the number of fine-tuning epochs?

**Comment by ddofer** [comment]
> What is the purpose of fine-tuning an already-trained model?

additional epochs over the data = better results, so long as you stop before overfitting starts.

**Comment by BenjyNStrauss** [comment]
Is there any way you can tell when overfitting will start (without actually running those tests)?

**Comment by nadavbra** [comment]
That's a general machine learning question not specifically related to ProteinBERT. I'd try asking in other ML communities.
