### ISSUE TITLE
ValueError, set_weights error

### ISSUE THREAD

**Issue by yumengyann** [nadavbra/protein_bert#91]
Hi when I run ProteinBERT demo.ipynb,  "Fine-tune the model for the signal peptide benchmark"
I got this error

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 46
     38 model_generator = FinetuningModelGenerator(pretrained_model_generator, OUTPUT_SPEC, pretraining_model_manipulation_function = \
     39         get_model_with_hidden_layers_as_outputs, dropout_rate = 0.5)
     41 training_callbacks = [
     42     keras.callbacks.ReduceLROnPlateau(patience = 1, factor = 0.25, min_lr = 1e-05, verbose = 1),
     43     keras.callbacks.EarlyStopping(patience = 2, restore_best_weights = True),
     44 ]
---> 46 finetune(model_generator, input_encoder, OUTPUT_SPEC, train_set['seq'], train_set['label'], valid_set['seq'], valid_set['label'], \
     47         seq_len = 512, batch_size = 32, max_epochs_per_stage = 1, lr = 1e-04, begin_with_frozen_pretrained_layers = True, \
     48         lr_with_frozen_pretrained_layers = 1e-02, n_final_epochs = 1, final_seq_len = 1024, final_lr = 1e-05, callbacks = training_callbacks)
     51 # Evaluating the performance on the test-set
     53 results, confusion_matrix = evaluate_by_len(model_generator, input_encoder, OUTPUT_SPEC, test_set['seq'], test_set['label'], \
     54         start_seq_len = 512, start_batch_size = 32)

File D:\protein_bert\proteinbert\finetuning.py:56, in finetune(model_generator, input_encoder, output_spec, train_seqs, train_raw_Y, valid_seqs, valid_raw_Y, seq_len, batch_size, max_epochs_per_stage, lr, begin_with_frozen_pretrained_layers, lr_with_frozen_pretrained_layers, n_final_epochs, final_seq_len, final_lr, callbacks)
     52     model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr_with_frozen_pretrained_layers, \
     53             callbacks = callbacks, freeze_pretrained_layers = True)
     55 log('Training the entire fine-tuned model...')
---> 56 model_generator.train(encoded_train_set, encoded_valid_set, seq_len, batch_size, max_epochs_per_stage, lr = lr, callbacks = callbacks, \
     57         freeze_pretrained_layers = False)
     59 if n_final_epochs > 0:
     60     log('Training on final epochs of sequence length %d...' % final_seq_len)

File D:\protein_bert\proteinbert\model_generation.py:24, in ModelGenerator.train(self, encoded_train_set, encoded_valid_set, seq_len, batch_size, n_epochs, lr, callbacks, **create_model_kwargs)
     22 train_X, train_Y, train_sample_weigths = encoded_train_set
     23 self.dummy_epoch = (_slice_arrays(train_X, slice(0, 1)), _slice_arrays(train_Y, slice(0, 1)))
---> 24 model = self.create_model(seq_len, **create_model_kwargs)
     26 if lr is not None:
     27     model.optimizer.lr = lr

File D:\protein_bert\proteinbert\model_generation.py:140, in FinetuningModelGenerator.create_model(self, seq_len, freeze_pretrained_layers)
    137 model = keras.models.Model(inputs = model_inputs, outputs = output_layer)
    138 model.compile(loss = loss, optimizer =self.optimizer_class(learning_rate = self.lr, **self.other_optimizer_kwargs))
--> 140 self._init_weights(model)
    142 return model

File D:\protein_bert\proteinbert\model_generation.py:45, in ModelGenerator._init_weights(self, model)
     42     self._train_for_a_dummy_epoch(model)
     44 if self.model_weights is not None:
---> 45     model.set_weights(copy_weights(self.model_weights))
     47 if self.optimizer_weights is not None:
     48     if len(self.optimizer_weights) == len(model.optimizer.variables()):

File C:\Anaconda\Lib\site-packages\keras-3.3.3-py3.11.egg\keras\src\layers\layer.py:666, in Layer.set_weights(self, weights)
    664 layer_weights = self.weights
    665 if len(layer_weights) != len(weights):
--> 666     raise ValueError(
    667         f"You called `set_weights(weights)` on layer '{self.name}' "
    668         f"with a weight list of length {len(weights)}, but the layer "
    669         f"was expecting {len(layer_weights)} weights."
    670     )
    671 for variable, value in zip(layer_weights, weights):
    672     if variable.shape != value.shape:

ValueError: You called `set_weights(weights)` on layer 'functional_5' with a weight list of length 146, but the layer was expecting 145 weights.
________________________________________

Do you know why?

**Comment by Anshullllllll** [comment]
ValueError: You called `set_weights(weights)` on layer 'functional_2' with a weight list of length 146, but the layer was expecting 145 weights.

I am also facing the same error if u find something helpful please let us know here....
@nadavbra @ddofer @PrathamSoni @JudeWells @yumengyann

**Comment by shrutikkharkar** [comment]
ValueError: You called `set_weights(weights)` on layer 'functional_2' with a weight list of length 146, but the layer was expecting 145 weights.

Facing the same issue..

**Comment by nadavbra** [comment]
Please look at the history of closed issues, this has been reported and solved many times in the past (if I remember correctly it has to do with package versions).
