### ISSUE TITLE
Missing MajorPTMs train CSV file

### ISSUE THREAD

**Issue by YanjingLiLi** [nadavbra/protein_bert#94]
Hi authors, I think the proteinBert benchmark data folder misses the train CSV for phophositePTMs (https://github.com/nadavbra/protein_bert/tree/master/protein_benchmarks). Can you help check this? Thanks.

**Comment by ddofer** [comment]
As I recall, it was too large to upload on github. We uploaded it elsewhere (maybe in the paper's supplementary?).
REgardless, you can download the dataset's source from phosphoPTM. I think we just did a random split then .
