### ISSUE TITLE
User-local installation fails on Mac

### ISSUE THREAD

**Issue by shiraz-shah** [nadavbra/protein_bert#98]
I tried a local install like so:
`python3 setup.py install --prefix ~/Library/Python/3.9/lib/python/site-packages`
but that fails with:
```
error: Setup script exited with error: SandboxViolation: mkdir('~/Library/Caches/com.apple.python/private/var/folders/db/b5k3hsv140sfpkz0727gw2rm0000gn/T/easy_install-60mt513h', 511) {}

The package setup script has attempted to modify files on your system
that are not within the EasyInstall build area, and has been aborted.

This package cannot be safely installed by EasyInstall, and may not
support alternate installation locations even if you run its setup
script by hand.  Please inform the package's author and the EasyInstall
maintainers to find out if a fix or workaround is available.
```
Is a local installation possible?

**Comment by nadavbra** [comment]
Hi @shiraz-shah,

I'm not familiar with this way of installing. Have you tried following the instructions on our README and look through past Issues that have faced similar installation problems?

**Comment by ddofer** [comment]
Looks like you lack permissions (sandbox). Unrelated to the package. Try maybe pip install vs easy setup?
